spring:
  config:
    import: optional:configserver:http://config-server:8888
  kafka:
    bootstrap-servers: kafka:9092
    topic:
      notification-payment-success: notification.payment-success

order-service:
  base-url: ${ORDER_SERVICE_BASE_URL:http://order-service:8087}

notification:
  mail:
    from: test@example.com
