spring:
  application:
    name: cart-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      group-id: cart-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/cart_service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:${MYSQL_USERNAME:root}}
    password: ${SPRING_DATASOURCE_PASSWORD:${MYSQL_PASSWORD:root}}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_DEFAULT_ZONE:http://service-registry:8761/eureka/}

price-service:
  base-url: http://price-service

stock-service:
  base-url: http://stock-service

product-service:
  base-url: http://product-service

address-service:
  base-url: http://address-service

user-service:
  base-url: http://user-service

order-service:
  base-url: http://order-service

payment-service:
  base-url: http://payment-service

app:
  kafka:
    request-timeout-ms: 10000
    topics:
      payment-link-request: payment-link.ensure.request.v1
      payment-link-response: payment-link.ensure.response.v1

server:
  port: 8086

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  error:
    include-message: always
    include-stacktrace: always

