spring:
  application:
    name: order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/order_service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:${MYSQL_USERNAME:root}}
    password: ${SPRING_DATASOURCE_PASSWORD:${MYSQL_PASSWORD:root}}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_DEFAULT_ZONE:http://service-registry:8761/eureka/}

payment-service:
  base-url: ${PAYMENT_SERVICE_BASE_URL:http://payment-service:8088}

app:
  kafka:
    topics:
      notification-order-placed: notification.order-placed
      notification-payment-success: notification.payment-success

server:
  port: 8087
  error:
    include-message: always
    include-stacktrace: always

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

