spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      group-id: payment-service

server:
  port: 8088

order-service:
  base-url: ${ORDER_SERVICE_BASE_URL:http://order-service:8087}

razorpay:
  api-base-url: https://api.razorpay.com/v1
  key-id: rzp_test_Saz0LB08MOvmbo
  key-secret: Rzo0PMC3rnWC0GNtYj1WLJ4n
  webhook-secret: Rzo0PMC3rnWC0GNtYj1WLJ4n

app:
  kafka:
    topics:
      payment-link-request: payment-link.ensure.request.v1
      payment-link-response: payment-link.ensure.response.v1

management:
  endpoints:
    web:
      exposure:
        include: health,info

